### ISSUE TITLE
[Bug]: Another invalid "var-use-before-def", 101 flag on a valid GetProperty call

### ISSUE THREAD

**Issue by HGS-jimpendleton** [interactive-data-language/vscode-idl#22]
### Current Behavior

The following code generates a "var-use-before-def" error by the plug-in parser on the variable "MinSoftwareversion", but there's not a thing wrong with it.
    If (Serial_Number eq !null) then Begin
        ((self.d)['blah'])->GetProperty, CSHDetector_Minimum_Software_Version = $
            MinSoftwareVersion
    EndIf

### Expected Behavior

The plug-in parser should not issue a warning or error state on this syntax.  Every time there's a potential output variable as a keyword, the code is going to be marked up to the point of the mark-up being totally ignorable unless we can interactively turn off warnings like this through a context menu.  The descriptions of the toggles in Preferences aren't particularly useful for situations like this.

### Steps to Reproduce

Copy the example code.  Easy peasy.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

9.0

**Comment by znorman-harris** [comment]
I'm going to mark this as won't fix. From a pure IDL perspective, you aren't wrong that the code is technically correct, but think about this problem as a programmer.

Technically, no where in your code is "Serial_Number" defined. If this is a routine definition I would expect to have arguments and keywords where, one of them, would be "Serial_Number" so that there's a source for it and this wouldn't be an issue.

For me, a big reason we have a lot of these errors is to help the flow of code follow patterns that new users to IDL can quickly pick up.

I know there's some big opinions in that statement, so hit me up on teams if you want to chat, Jim and maybe there's a middle ground here!
