### ISSUE TITLE
[Feature]: Control IDL keyword argument spacing

### ISSUE THREAD

**Issue by gsf-elefebvre** [interactive-data-language/vscode-idl#24]
### Description

Say If I have the idl procedure with a keyword argument
```
pro myProcedure, KEYWORD=keyword
  compile_opt idl2
  newVar=keyword
end
```

Autoformat will add spaces around the "=" for all cases
```
pro myProcedure, KEYWORD = keyword
  compile_opt idl2
  newVar = keyword
end
```
The style I'm used to though is no spaces around the "=" for keyword arguments
```
pro myProcedure, KEYWORD=keyword
  compile_opt idl2
  newVar = keyword
end
```

### Why it Matters

I can't use the auto formatter without this feature.

### Suggested Behavior

Add in a new settings option to control the spacing for keyword arguments

**Comment by znorman-harris** [comment]
When it comes to formatting, the spirit of what is in the extension is modeled after Prettier.

The goal is we have controls for the style of your code (i.e. upper/lower case, dot/arrow) and not the mechanical appearance of your code.

We also don't want to add controls for every option because that defeats the purpose of having code with a consistent appearance between users. There's a nice "inspirational" read on Prettier's design choice [here](https://prettier.io/docs/en/option-philosophy) that we follow.

I also added a new page to our docs that you can find [here](https://interactive-data-language.github.io/vscode-idl/code-comments/formatting.html#background-and-design) which captures this.

Personally, I wasn't a fan of keyword spacing (or lower case) at first as I used to write code with the same style as you. I gave it a whirl and I quite like the new look-and-feel using the defaults for formatting that we (Me + IDL team) decided on.

If you want to chat, feel free to ping me on teams!
