### ISSUE TITLE
[Bug]: Invalid "unknown-kw", 97 when passing keywords to obj_destroy

### ISSUE THREAD

**Issue by liamw1** [interactive-data-language/vscode-idl#39]
### Current Behavior

When passing keywords into obj_destroy for object cleanup, the usage of any keyword gets incorrectly flagged as an error.

### Expected Behavior

This should not be flagged as an error.

### Steps to Reproduce

1. Create an object with a cleanup method that takes a keyword as a parameter
2. Construct an instance of that object
3. Call obj_destroy on that instance with the keyword set

Example code:

```
pro TestClass__define
  !null = {TestClass, data:ptr_new()}
end

function TestClass::init, value
  self.data = ptr_new(0)
  *self.data = value
  return, 1
end

pro TestClass::Cleanup, keyword = keyword
  if keyword_set(keyword) then print, "keyword set!"
  print, "I have been called!"
end

function TestClass::get
  return, *self.data
end

pro test
  compile_opt idl2

  obj = obj_new('TestClass', 1)
  
  obj_destroy, obj, /keyword
end
```

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

8.9

**Comment by znorman-harris** [comment]
Thanks for reporting and for the small code snippet!

Re-worked how we get the routine for obj_destroy behind the scenes and it will be fixed in the next release. I'll add a note to this issue when I publish a new release which might be tomorrow or early next week depending on my schedule.

For the fix: if we detect the type of your input variable (`obj` in your code), we will infer that `obj_destroy` calls the `testclass::cleanup` method (as long as we know about it). It will also show this through hover help and auto-complete.

Here's a screenshot showing no reported problems and, hovering over `obj_destroy`, now shows you the docs for your method.

![image](https://github.com/user-attachments/assets/e8e5172a-ec47-4124-aa76-fdbf299bc624)
