### ISSUE TITLE
[Bug]: Invalid "illegal-dictionary-op", 89 when type of key can't be determined

### ISSUE THREAD

**Issue by liamw1** [interactive-data-language/vscode-idl#40]
### Current Behavior

Operations on result of dictionary access can give false errors under certain circumstances.

### Expected Behavior

The error shouldn't appear

### Steps to Reproduce

1. Create a dictionary
2. Apply an operation to the result of a dictionary access with a key whose type can't be statically determined
3. Observe the error

Example Code:

```
function get_dir, arg
  if arg eq 0 then return, 'NSEW' else return, 0
end

pro test
  compile_opt idl2

  sign = dictionary('N',1,'S',-1,'E',1,'W',-1)
  num = 1.0 * sign[strmid(get_dir(0),1,1)]
  
  print, num
end
```

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

8.9

**Comment by znorman-harris** [comment]
This is an interesting one (and one that's hard to say is a bug).

Technically, when we don't know the type returned from a function, we use `any` since it could be anything.

The problem in this case is that, for some IDL functions, they accept an array *or* a scalar for arguments. In this case, `strtrim()` has a special type called `ArrayPromotion<String>` which will return an array of strings if an argument to `strtrim()` is an array.

So, the logic in the code (and detecting a potential problem) is actually doing the *exact* thing it was meant to.

If that sounds weird, here's the catch: if you index a `dictionary()` with an array, then you actually get a dictionary back from IDL (weird, I know). So your code that you shared could break if you accidentally passed in an array to strtrim because you would be multiplying a scalar and a dictionary which is invalid.

Because we don't know the type, it's actually doing what I would expect it to.

Let me stew on this a bit more and think about what the right thing to do here would be.

Good news: If you didn't notice, you can use the code actions to disable reporting the problem for your line:

![image](https://github.com/user-attachments/assets/377c6f7b-993a-46b5-928e-b8fab76eada9)

**Comment by chris-torrence** [comment]
Definitely tricky, but I think the current behavior is okay. If you accept that you're using types in IDL, then it all seems to be consistent. For example, look at the following program:
![image](https://github.com/user-attachments/assets/0290f502-7148-46b5-9625-f32c568f438c)

It correctly underlines the line at the very end as an error, since you're clearly passing an array into the dictionary. However, for the "any" function, it doesn't underline because there isn't enough information (maybe it should underline?).

Recommend that for these unusual cases that you just disable error reporting for the individual line, or the entire file if you're doing that often. You can also disable all errors of that type for all files. I've had to do that for a few of the errors since our IDL codebase is somewhat old and crufty. :-)

**Comment by znorman-harris** [comment]
Alright, so if the behavior is OK, then I'm good with that. I think another thing we could do to work around this problem would be to detect the returned type from functions without docs for types.

If we were doing that, then we would see from the original snippet that we had a scalar being returned and arrays (also dictionaries) wouldn't come into the equation and we wouldn't see the error.

I'll see if I can get a first pass of that together later this week and, once it is wrapped up, then we can get a minor release to the extension out.

**Comment by znorman-harris** [comment]
Quick update: Just published a new version of the extension to fix the other issues. I need to think about getting return types from functions a little more as there's some complexities I didn't think about originally.

**Comment by znorman-harris** [comment]
Alright, I'm gong to close this since the latest develop branch solves this problem.

I updated our type detection logic to automatically detect the type from "return" when you don't have docs. 

Given that we can statically determine the return type, the original type error goes away, and you shouldn't run into this problem again.

I need to do a little more testing but will hopefully have a release out later this week.
