### ISSUE TITLE
[Bug]: Reordering function argument doc parameters can cause "ptr-de-ref-illegal", 94 errors

### ISSUE THREAD

**Issue by liamw1** [interactive-data-language/vscode-idl#41]
### Current Behavior

Certain functions can give false errors depending on the ordering of documentation parameters.

### Expected Behavior

The errors that appear should not depend on the order of documentation parameters.

### Steps to Reproduce

1. Write a procedure or function that takes a ptr argument
2. Dereference that pointer in the function
3. Add documentation for the ptr argument specifying that it's in, ptr, required
4. Observe that an error appears on the dereferencing of the ptr argument
5. Reorder the documentation for the ptr argument to in, required, ptr
6. Observe that the error no longer appears

Example code:

```
;+
; :Arguments:
;    arg: in, ptr, required
;-
pro print_out, arg
  print, *arg
end
```

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

8.9

**Comment by znorman-harris** [comment]
For IDL, we follow (mostly) the IDL Doc standard for how to document your code. 

As part of this, the order that we expect is:

1. Direction (`in`, `out`, or `bidirectional`)
2. Required (literal `required` or `optional`)
3. Data type
4. (Optional) private or not

This is captured in our main examples for documentation [here](https://interactive-data-language.github.io/vscode-idl/code-comments/#docs-style) and a little more detail at the bottom of [this](https://interactive-data-language.github.io/vscode-idl/code-comments/auto_doc.html) page.

This might be a won't fix item since it break from the pattern for docs, but I'll ask the team and see what they think.

If you do use auto-doc and format on save, it will automatically add the docs in the right formatting for you to help save time and automate the process.

Let me know if you have any other thoughts!

**Comment by liamw1** [comment]
Ah, ok. If the IDL Doc specification defines a specific ordering, then that's fair. I guess I just assumed that "required", "optional", "in", etc. were like keywords that could appear in any order.

**Comment by znorman-harris** [comment]
Yeah, there is an order to it which we try to enforce. The tricky part is types can be anything, so there's not an easy way to check or make sure you have specified the right information without it.

I'll go ahead and close this for now as not an issue.

If you have some other thoughts or ideas for the docs, let us know and we are happy to discuss!
